# Generated by Django 3.0.1 on 2020-02-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('region', models.CharField(blank=True, max_length=40, null=True)),
                ('owner', models.CharField(blank=True, max_length=60, null=True)),
                ('year_closed', models.IntegerField(blank=True, null=True)),
                ('year_demolished', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Distilleries',
            },
        ),
    ]
