# Generated by Django 3.0.5 on 2020-04-25 15:59

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('distilleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillery',
            name='geolocation',
            field=location_field.models.spatial.LocationField(default=django.contrib.gis.geos.point.Point(1.0, 1.0), srid=4326),
        ),
    ]
