# Generated by Django 3.0.5 on 2020-04-26 03:39

from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('distilleries', '0002_distillery_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distillery',
            name='geolocation',
            field=location_field.models.spatial.LocationField(srid=4326),
        ),
    ]
