# Generated by Django 3.0.5 on 2020-04-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distilleries', '0003_auto_20200426_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillery',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
