# Generated by Django 3.0.5 on 2020-04-28 02:25

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('region', models.CharField(blank=True, max_length=40, null=True)),
                ('owner', models.CharField(blank=True, max_length=60, null=True)),
                ('year_established', models.IntegerField(blank=True, null=True)),
                ('year_closed', models.IntegerField(blank=True, null=True)),
                ('year_demolished', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('geolocation', location_field.models.spatial.LocationField(blank=True, null=True, srid=4326)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Distilleries',
            },
        ),
    ]
