# Generated by Django 3.0.5 on 2020-04-29 04:37

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('region', models.CharField(blank=True, max_length=40, null=True)),
                ('owner', models.CharField(blank=True, max_length=60, null=True)),
                ('year_established', models.IntegerField(blank=True, null=True)),
                ('year_closed', models.IntegerField(blank=True, null=True)),
                ('year_demolished', models.IntegerField(blank=True, null=True)),
                ('geolocation', location_field.models.spatial.LocationField(blank=True, null=True, srid=4326)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Distilleries',
            },
        ),
        migrations.CreateModel(
            name='Scotch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('distillery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Distillery')),
            ],
            options={
                'verbose_name_plural': 'Scotches',
            },
        ),
        migrations.CreateModel(
            name='ABCInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200)),
                ('unique_id', models.CharField(help_text='Unique to product but not size/price', max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('product_uri', models.URLField(blank=True, null=True)),
                ('hierarchy_division', models.CharField(blank=True, max_length=50, null=True)),
                ('hierarchy_class', models.CharField(blank=True, max_length=50, null=True)),
                ('hierarchy_category', models.CharField(blank=True, max_length=50, null=True)),
                ('hierarchy_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hierarchy_detail', models.CharField(blank=True, max_length=50, null=True)),
                ('hierarchy_fact', models.CharField(blank=True, max_length=50, null=True)),
                ('hierarchy_imported', models.CharField(blank=True, max_length=50, null=True)),
                ('hierarchy_flavored', models.CharField(blank=True, max_length=50, null=True)),
                ('hierarchy_vap', models.CharField(blank=True, max_length=50, null=True)),
                ('scotch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Scotch')),
            ],
            options={
                'unique_together': {('name', 'size')},
            },
        ),
    ]
