# Generated by Django 3.0.5 on 2020-04-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abcinfo',
            options={'verbose_name_plural': 'ABC Info'},
        ),
        migrations.RemoveField(
            model_name='distillery',
            name='image_url',
        ),
        migrations.AddField(
            model_name='abcinfo',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scotch',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
