# Generated by Django 3.0.5 on 2020-04-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200429_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillery',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
