# Generated by Django 3.0.5 on 2020-04-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_distillery_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcinfo',
            name='sku',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='abcinfo',
            unique_together=set(),
        ),
    ]
