# Generated by Django 3.0.5 on 2020-05-09 18:07

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=40, null=True)),
                ('region', models.CharField(blank=True, max_length=40, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=60, null=True)),
                ('year_established', models.IntegerField(blank=True, null=True)),
                ('year_closed', models.IntegerField(blank=True, null=True)),
                ('year_demolished', models.IntegerField(blank=True, null=True)),
                ('geolocation', location_field.models.spatial.LocationField(blank=True, null=True, srid=4326)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Company')),
            ],
            options={
                'verbose_name_plural': 'Distilleries',
            },
        ),
        migrations.CreateModel(
            name='Scotch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('distillery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.Distillery')),
            ],
            options={
                'verbose_name_plural': 'Scotches',
            },
        ),
    ]
