# Generated by Django 3.0.5 on 2020-05-09 19:28

from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hq_location',
            field=location_field.models.spatial.LocationField(blank=True, null=True, srid=4326),
        ),
    ]
